[DatabaseService]
    ; Use MySQL database service in Swarm
    StorageProvider = "OpenSim.Data.MySQL.dll"
    ConnectionString = "Data Source=db;Port=3307;Database=os_regiao0001;User ID=osuser;Password=${DB_PASSWORD};Old Guids=true;SslMode=None;"

[AssetService]
    DefaultAssetLoader = "OpenSim.Framework.AssetLoader.Filesystem.dll"
    AssetLoaderArgs = "assets/AssetSets.xml"
    AssetServerURI = "https://asset.oligrid.net"

[InventoryService]
    InventoryServerURI = "https://inventory.oligrid.net"

[GridInfo]
    GridInfoURI = "https://grid.oligrid.net"

[GridService]
    GridServerURI = "https://private-grid.oligrid.net"
    Gatekeeper = "https://hg.oligrid.net"

[EstateService]
    EstateServerURI = "https://private-user.oligrid.net"

[AvatarService]
    AvatarServerURI = "https://private-user.oligrid.net"

[PresenceService]
    PresenceServerURI = "https://private-user.oligrid.net"

[UserAccountService]
    UserAccountServerURI = "https://private-user.oligrid.net"

[GridUserService]
    GridUserServerURI = "https://private-user.oligrid.net"

[FriendsService]
    FriendsServerURI = "https://private-user.oligrid.net"

[Messaging]
    Gatekeeper = "https://hg.oligrid.net"
