[Startup]
    ; Choose GridHypergrid architecture for our oligrid simulator container
    Include-Architecture = "config-include/GridHypergrid.ini"

    ; Set console to basic mode so it runs cleanly inside Docker logs
    console = "Basic"
