# docker-compose -f docker-compose-mongodb.yml up -d
# client mongodb://admin:8OTkIpiTerF1zZ5VXoxN@localhost:27017/?authSource=admin

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass123
      MONGO_INITDB_DATABASE: opensim
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpass123
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpass123@mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: webadmin
      ME_CONFIG_BASICAUTH_PASSWORD: webpass123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongo_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  mongo_network:
    driver: bridge
